challenge finished
Han-Zhang-fuze/c0522-code-solutions pull request #22
Opened 2022-05-15 18:16 UTC by Han-Zhang-fuze

![Animation](https://user-images.githubusercontent.com/103379415/168487778-dee63534-2017-4c03-ade7-ca3e73bf582b.gif)

2022-05-15 20:07 UTC, codingcodymiller requested changes

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  width: 60%;
This name doesn't match its measurement 🤔

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
I would just create a class so that this styling is reusable

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +#btn {
Use `class`es, not `id`s

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  width: 50%;
Why not use a proper `column` class?

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  width: 40%;
Why not use a proper `column` class?

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
This should just be your plain `container` class

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
I see that this _already is_ your plain `container` class, on line 8. Be careful not to unnecessarily duplicate styling 👀

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Why not just use a `row`?

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  width: 60%;
Why not use a proper `column` class?

2022-05-15 20:07 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  width: 40%;
Why not use a proper `column` class?

2022-05-17 18:49 UTC, codingcodymiller requested changes

2022-05-17 18:49 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    <div class="row container justify-content-spacebetween">
No one element should be both a `container` and a `row`. Instead, you should make an element with the `container` class that has a child with the `row` class

2022-05-17 18:49 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    <div class="row container justify-content-spacebetween">
This issue is present in multiple other places in your code, please make sure it is addressed in all instances.

2022-05-17 22:23 UTC, Han-Zhang-fuze commented
![May-17-2022 15-21-17](https://user-images.githubusercontent.com/103379415/168922120-81629049-17d7-464d-9ef0-cb3c92ea812e.gif)

2022-05-18 01:12 UTC, Han-Zhang-fuze commented
![May-17-2022 18-11-30](https://user-images.githubusercontent.com/103379415/168936907-2b04592d-9783-480b-8923-af134bbb69c7.gif)

2022-05-18 17:39 UTC, codingcodymiller requested changes

2022-05-18 17:39 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </nav>
No `column` classes?

2022-05-18 17:39 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </div>
No `column` classes?

2022-05-18 17:39 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +    <div class="container row">
No one element should be both a `container` and a `row`, I believe I mentioned this in a previous review.

2022-05-18 17:39 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Maybe a `column-two-thirds` with some padding 🤔

2022-05-18 17:39 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
These seem like they should just be some padding utility classes added to a `column-full` element

2022-05-20 21:55 UTC, codingcodymiller approved these changes
Fantastic work, Han!! This is all looking great, excellent revisions 👏 👏 👏

2022-05-20 21:56 UTC, merged